### ISSUE TITLE
Linker: Incorrect Thread Local Variable symbol resolution

### ISSUE THREAD

**Issue by randomNinja1000** [kubkon/zld#124]
I found an issue with the zig linker on macOS and I didn't know if I needed to file it here or in the ziglang report.
I filed it in the ziglang report, but I'm cross posting it here to raise awareness to it and in case the right thing was actually to file here!

Anyhow, here is the issue https://github.com/ziglang/zig/issues/19221

**Comment by kubkon** [comment]
I actually very much appreciate you taking the time to file it in both places - thank you so much!

**Comment by kubkon** [comment]
Fixed in https://github.com/kubkon/zld/commit/0b7bef19b6b43d66667f8bd35701fa45ebee7f16
